{-

Author: Rohit Jha
File: PE002.hs
July 5, 2013

Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

-}

main = putStrLn $ show $ sum [ x | x <- takeWhile (<= 4000000) fibs, even x]
	where
		fibs = 1 : 2 : zipWith (+) fibs (tail fibs)

{-
4613732

real	0m0.003s
user	0m0.000s
sys		0m0.000s
-}
