/*

Author: Rohit Jha
File: PE002.c
July 5, 2013

Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

*/

#include <stdio.h>

int main() {
	long limit = 4000000;
	long x = 1;
	long y = 1;
	long sum = 0;
	
	while(sum < limit)
	{
		sum += (x+y);
		x = x + 2*y;
		y = 2*x - y;
	}
	
	printf ("%d\n", sum);
	return 0;
}

/*
4613732

real	0m0.001s
user	0m0.000s
sys		0m0.000s
*/
