#! /usr/bin/env python
# PE002.py

'''

Author: Rohit Jha
File: PE002.py
July 5, 2013

Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

'''

limit = 4000000
x, y, sum = 1, 1, 0
 
while (sum < limit):
	sum += (x + y)
	x, y = x + 2*y, 2*x + 3*y
 
print(sum)

'''
4613732

real	0m0.043s
user	0m0.040s
sys		0m0.000s
'''
